name: Update Userscript Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Update Version
        run: |
          VERSION=$(grep -oE '@version[[:space:]]+[0-9]+\.[0-9]+\.[0-9]+' olx-sponsored-begone.user.js | awk '{print $2}')
          if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Error: Invalid version format: $VERSION"
            exit 1
          fi
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          if [ "$PATCH" -lt 9 ]; then
            NEW_VERSION="$MAJOR.$MINOR.$((PATCH+1))"
          else
            NEW_VERSION="$MAJOR.$((MINOR+1)).0"
          fi
          sed -i "s/@version\s\+$VERSION/@version          $NEW_VERSION/" olx-sponsored-begone.user.js
          sed -i "s/@version\s\+$VERSION/@version          $NEW_VERSION/" olx-sponsored-begone.js
      - name: Verify Version Update
        run: |
          if ! grep -q "@version          $NEW_VERSION" olx-sponsored-begone.user.js || \
             ! grep -q "@version          $NEW_VERSION" olx-sponsored-begone.js; then
            echo "Error: Version update failed"
            exit 1
          fi
      - name: Commit and Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Bump version to $NEW_VERSION"
          git push
